let products = [
    {
        id:1001,
        title: "Cat Food, 25lb bag",
        description: "A 25 pound bag of <em>irresistible</em>, " + "organic goodness for your cat.",
        price: 2000,
        image: "images/product-fullsize.jpg",
        availableInventory: 10,
        rating: 3,
    },
    {
        id:1002,
        title: "Cookie",
        description: "A great taste.",
        price: 12,
        image: "images/product-fullsize.jpg",
        availableInventory: 7,
        rating: 2,
    },
    {
        id:1003,
        title: "Comb",
        description: "A hair comb",
        price: 2000,
        image: "images/product-fullsize.jpg",
        availableInventory: 5,
        rating: 5,
    },
    {
        id:1004,
        title: "Bottle Water",
        description: "Al ain bottled water.",
        price: 50,
        image: "images/product-fullsize.jpg",
        availableInventory: 3,
        rating: 1,
    },
    {
        id:1005,
        title: "Bottle Water",
        description: "Al ain bottled water.",
        price: 12,
        image: "images/product-fullsize.jpg",
        availableInventory: 3,
        rating: 1,
    },
]